optionsLangList = [
{ value:'afr',     label : 'Afrikaan',                       },
{ value:'ara',     label : 'Arabic',                         },
{ value:'aze',     label : 'Azerbaijani',                    },
{ value:'bel',     label : 'Belarusian',                     },
{ value:'ben',     label : 'Bengali',                        },
{ value:'bul',     label : 'Bulgaran',                       },
{ value:'cat',     label : 'Catalan',                        },
{ value:'ces',     label : 'Czech',                          },
{ value:'chi_sim', label : 'Chinse',                         },
{ value:'chi_tra', label : 'Traditonal Chinese',             },
{ value:'chr',     label : 'Cherokee',          },
{ value:'dan',     label : 'Danish  ',          },
{ value:'deu',     label : 'German  ',          },
{ value:'ell',     label : 'Greek   ',          },
{ value:'eng',     label : 'English ',  },
{ value:'enm',     label : 'English (Old)        ',          },
{ value:'meme',    label : 'Internet Meme        ',          },
{ value:'epo',     label : 'Esperanto            ',          },
{ value:'epo_alt', label : 'Esperanto alternative',          },
{ value:'equ',     label : 'Math    ',          },
{ value:'est',     label : 'Estonian',          },
{ value:'eus',     label : 'Basque  ',          },
{ value:'fin',     label : 'Finnish ',          },
{ value:'fra',     label : 'French  ',          },
{ value:'frk',     label : 'Frankish',          },
{ value:'frm',     label : 'French (Old)         ',          },
{ value:'glg',     label : 'Galician',          },
{ value:'grc',     label : 'Ancient Greek        ',          },
{ value:'heb',     label : 'Hebrew  ',          },
{ value:'hin',     label : 'Hindi   ',          },
{ value:'hrv',     label : 'Croatian',          },
{ value:'hun',     label : 'Hungarian            ',          },
{ value:'ind',     label : 'Indonesian           ',          },
{ value:'isl',     label : 'Icelandic            ',          },
{ value:'ita',     label : 'Italian ',          },
{ value:'ita_old', label : 'Italian (Old)        ',          },
{ value:'jpn',     label : 'Japanese',          },
{ value:'kan',     label : 'Kannada ',          },
{ value:'kor',     label : 'Korean  ',          },
{ value:'lav',     label : 'Latvian ',          },
{ value:'lit',     label : 'Lithuanian           ',          },
{ value:'mal',     label : 'Malayalam            ',          },
{ value:'mkd',     label : 'Macedonian           ',          },
{ value:'mlt',     label : 'Maltese ',          },
{ value:'msa',     label : 'Malay   ',          },
{ value:'nld',     label : 'Dutch   ',          },
{ value:'nor',     label : 'Norwegian            ',          },
{ value:'pol',     label : 'Polish  ',          },
{ value:'por',     label : 'Portuguese',   selected : 'selected'       },
{ value:'ron',     label : 'Romanian',          },
{ value:'rus',     label : 'Russian ',          },
{ value:'slk',     label : 'Slovakian            ',          },
{ value:'slv',     label : 'Slovenian            ',          },
{ value:'spa',     label : 'Spanish ',          },
{ value:'spa_old', label : 'Old Spanish          ',          },
{ value:'sqi',     label : 'Albanian',          },
{ value:'srp',     label : 'Serbian (Latin)      ',          },
{ value:'swa',     label : 'Swahili ',          },
{ value:'swe',     label : 'Swedish ',          },
{ value:'tam',     label : 'Tamil   ',          },
{ value:'tel',     label : 'Telugu  ',          },
{ value:'tgl',     label : 'Tagalog ',          },
{ value:'tha',     label : 'Thai    ',          },
{ value:'tur',     label : 'Turkish ',          },
{ value:'ukr',     label : 'Ukrainian            ',          },
{ value:'vie',     label : 'Vietnamese           ',          },

];

const select = document.querySelector('#langsel');

optionsSelect = () => {
    var options="";
    optionsLangList.map((item) => {
        options+=`<option value="${item.value}" ${item.selected ? item.selected : ''}>${item.label}</option>`
    });

    console.log(options);
    select.innerHTML = options;
}

optionsSelect();
/*

{ value='afr'     label = 'Afrikaan  selected = ''         },
{ value='ara'     label = 'Arabic'                selected = ''         },
{ value='aze'     label = 'Azerbaijani'           selected = ''         },
{ value='bel'     label = 'Belarusian'            selected = ''         },
{ value='ben'     label = 'Bengali'               selected = ''         },
{ value='bul'     label = 'Bulgaran'              selected = ''         },
{ value='cat'     label = 'Catalan'               selected = ''         },
{ value='ces'     label = 'Czech'                 selected = ''         },
{ value='chi_sim' label = 'Chinse'                selected = ''         },
{ value='chi_tra' label = 'Traditonal Chinese'    selected = ''         },
{ value='chr'     label = 'Cherokee             ' selected = ''         },
{ value='dan'     label = 'Danish               ' selected = ''         },
{ value='deu'     label = 'German               ' selected = ''         },
{ value='ell'     label = 'Greek                ' selected = ''         },
{ value='eng'     label = 'English              ' selected = 'selected' },
{ value='enm'     label = 'English (Old)        ' selected = ''         },
{ value='meme'    label = 'Internet Meme        ' selected = ''         },
{ value='epo'     label = 'Esperanto            ' selected = ''         },
{ value='epo_alt' label = 'Esperanto alternative' selected = ''         },
{ value='equ'     label = 'Math                 ' selected = ''         },
{ value='est'     label = 'Estonian             ' selected = ''         },
{ value='eus'     label = 'Basque               ' selected = ''         },
{ value='fin'     label = 'Finnish              ' selected = ''         },
{ value='fra'     label = 'French               ' selected = ''         },
{ value='frk'     label = 'Frankish             ' selected = ''         },
{ value='frm'     label = 'French (Old)         ' selected = ''         },
{ value='glg'     label = 'Galician             ' selected = ''         },
{ value='grc'     label = 'Ancient Greek        ' selected = ''         },
{ value='heb'     label = 'Hebrew               ' selected = ''         },
{ value='hin'     label = 'Hindi                ' selected = ''         },
{ value='hrv'     label = 'Croatian             ' selected = ''         },
{ value='hun'     label = 'Hungarian            ' selected = ''         },
{ value='ind'     label = 'Indonesian           ' selected = ''         },
{ value='isl'     label = 'Icelandic            ' selected = ''         },
{ value='ita'     label = 'Italian              ' selected = ''         },
{ value='ita_old' label = 'Italian (Old)        ' selected = ''         },
{ value='jpn'     label = 'Japanese             ' selected = ''         },
{ value='kan'     label = 'Kannada              ' selected = ''         },
{ value='kor'     label = 'Korean               ' selected = ''         },
{ value='lav'     label = 'Latvian              ' selected = ''         },
{ value='lit'     label = 'Lithuanian           ' selected = ''         },
{ value='mal'     label = 'Malayalam            ' selected = ''         },
{ value='mkd'     label = 'Macedonian           ' selected = ''         },
{ value='mlt'     label = 'Maltese              ' selected = ''         },
{ value='msa'     label = 'Malay                ' selected = ''         },
{ value='nld'     label = 'Dutch                ' selected = ''         },
{ value='nor'     label = 'Norwegian            ' selected = ''         },
{ value='pol'     label = 'Polish               ' selected = ''         },
{ value='por'     label = 'Portuguese           ' selected = ''         },
{ value='ron'     label = 'Romanian             ' selected = ''         },
{ value='rus'     label = 'Russian              ' selected = ''         },
{ value='slk'     label = 'Slovakian            ' selected = ''         },
{ value='slv'     label = 'Slovenian            ' selected = ''         },
{ value='spa'     label = 'Spanish              ' selected = ''         },
{ value='spa_old' label = 'Old Spanish          ' selected = ''         },
{ value='sqi'     label = 'Albanian             ' selected = ''         },
{ value='srp'     label = 'Serbian (Latin)      ' selected = ''         },
{ value='swa'     label = 'Swahili              ' selected = ''         },
{ value='swe'     label = 'Swedish              ' selected = ''         },
{ value='tam'     label = 'Tamil                ' selected = ''         },
{ value='tel'     label = 'Telugu               ' selected = ''         },
{ value='tgl'     label = 'Tagalog              ' selected = ''         },
{ value='tha'     label = 'Thai                 ' selected = ''         },
{ value='tur'     label = 'Turkish              ' selected = ''         },
{ value='ukr'     label = 'Ukrainian            ' selected = ''         },
{ value='vie'     label = 'Vietnamese           ' selected = ''         },

*/